# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.7"

volumes:
  ordererpemiracom:
  peer0pemilihanpemiracom:
  peer1pemilihanpemiracom:

networks:
  skripsi-evoting:
    external:
      name: skripsi-evoting

services:
  ordererpemiracom:
    deploy:
      placement:
        constraints:
          - node.Labels.name == manager
    container_name: orderer.pemira.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      # - ORDERER_OPERATIONS_LISTENADDRESS=orderer.pemira.com:8443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      # - ../organizations/ordererOrganizations/pemira.com/orderers/orderer.pemira.com/msp:/var/hyperledger/orderer/msp
      # - ../organizations/ordererOrganizations/pemira.com/orderers/orderer.pemira.com/tls/:/var/hyperledger/orderer/tls
      # - /home/ubuntu/skripsi-triana/network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/skripsi-triana/network-v2/organizations/ordererOrganizations/pemira.com/orderers/orderer.pemira.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/skripsi-triana/network-v2/organizations/ordererOrganizations/pemira.com/orderers/orderer.pemira.com/tls/:/var/hyperledger/orderer/tls
      - ordererpemiracom:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      # - 8443:8443
    networks:
      skripsi-evoting:
        aliases:
          - orderer.pemira.com

  peer0pemilihanpemiracom:
    deploy:
      placement:
        constraints:
          - node.Labels.name == manager
    container_name: peer0.pemilihan.pemira.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skripsi-evoting
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.pemilihan.pemira.com
      - CORE_PEER_ADDRESS=peer0.pemilihan.pemira.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pemilihan.pemira.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pemilihan.pemira.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pemilihan.pemira.com:7051
      - CORE_PEER_LOCALMSPID=PemilihanMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # - CORE_OPERATIONS_LISTENADDRESS=peer0.pemilihan.pemira.com:8444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0pemilihan"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/skripsi-triana/network-v2/organizations/peerOrganizations/pemilihan.pemira.com/peers/peer0.pemilihan.pemira.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/skripsi-triana/network-v2/organizations/peerOrganizations/pemilihan.pemira.com/peers/peer0.pemilihan.pemira.com/tls:/etc/hyperledger/fabric/tls
      - peer0pemilihanpemiracom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      # - 8444:8444
    networks:
      skripsi-evoting:
        aliases:
          - peer0.pemilihan.pemira.com

  peer1pemilihanpemiracom:
    deploy:
      placement:
        constraints:
          - node.Labels.name == worker1
    container_name: peer1.pemilihan.pemira.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skripsi-evoting
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.pemilihan.pemira.com
      - CORE_PEER_ADDRESS=peer1.pemilihan.pemira.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.pemilihan.pemira.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pemilihan.pemira.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pemilihan.pemira.com:8051
      - CORE_PEER_LOCALMSPID=PemilihanMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # - CORE_OPERATIONS_LISTENADDRESS=peer1.pemilihan.pemira.com:8445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1pemilihan"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/skripsi-triana/network-v2/organizations/peerOrganizations/pemilihan.pemira.com/peers/peer1.pemilihan.pemira.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/skripsi-triana/network-v2/organizations/peerOrganizations/pemilihan.pemira.com/peers/peer1.pemilihan.pemira.com/tls:/etc/hyperledger/fabric/tls
      - peer1pemilihanpemiracom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
      # - 8445:8445
    networks:
      skripsi-evoting:
        aliases:
          - peer1.pemilihan.pemira.com
