# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.7"

networks:
  skripsi-evoting:
    external:
      name: skripsi-evoting

services:
  cliPemilihan:
      container_name: cli
      image: hyperledger/fabric-tools:2.5.7
      labels:
        service: hyperledger-fabric
      tty: true
      stdin_open: true
      deploy:
        placement:
          constraints:
            - node.labels.name == manager
      environment:
        - GOPATH=/opt/gopath
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=DEBUG
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: /bin/bash
      volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      depends_on:
        - peer0.pemilihan.pemira.com
        - peer1.pemilihan.pemira.com
      networks:
        skripsi-evoting:
          aliases:
            - cli.pemilihan.pemira.com
